version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            cd venv/Scripts
            . activate
            sudo pip install --upgrade pip && pip install -r requirements.txt
      - save_cache:
          paths:
            - venv/Scripts
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            cd venv/Scripts
            . activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            cd venv/Scripts
            . activate
            make lint